Updated debianisation
svn path=/trunk/; revision=2030

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -18,6 +18,10 @@ nextupstreamversion=$(shell echo $(versionh).$$(expr $(versiont) + 1))
 # need to change the periods in it). The debian/* files must match.
 baselibname=$(shell grep -i '^GOFFICE_API_VER=[0-9]' configure | sed -e 's/^.*=/libgoffice-/' -e s/\\./-/g)
 
+pruntime=$(baselibname)
+pdevel=$(baselibname)-dev
+pdbg=libgoffice-dbg
+
 # These are used for cross-compiling and for saving the configure script
 # from having to guess our platform (since we know it already)
 DEB_HOST_GNU_TYPE   ?= $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
@@ -54,7 +58,7 @@ confflags := -v \
 	--prefix=/usr \
 	--mandir=\$${prefix}/share/man \
 	--infodir=\$${prefix}/share/info \
-	--with-html-dir=\$${prefix}/share/doc/$(baselibname)-dev/html
+	--with-html-dir=\$${prefix}/share/doc/$(pdevel)/html
 
 # FHS locations
 confflags +=	--prefix=/usr \
@@ -68,7 +72,7 @@ confflags +=    --disable-iso-c \
                 --enable-compile-warnings=maximum
 
 # Features
-confflags +=    --with-cairo --enable-gtk-doc
+confflags +=    --enable-static --with-cairo --enable-gtk-doc
 
 source-updates:
 	# Update files/links generated by autotools
@@ -86,8 +90,8 @@ source-updates:
 configure: configure-stamp
 configure-stamp:
 	dh_testdir
-	if ! test -r debian/$(baselibname).install ; then \
-		echo "Packaging files are not set up for base library name $(baselibname). Aborting." ; \
+	if ! test -r debian/$(pruntime).install ; then \
+		echo "Packaging files are not set up for base library name $(pruntime). Aborting." ; \
 		exit 1 ; \
 	fi
 	
@@ -140,11 +144,11 @@ install: build
 	# Install the package into debian/tmp
 	$(MAKE) -C build DESTDIR=$(CURDIR)/debian/tmp install 
 
-	# FIXME: where do we put the debug for the plugins?
-	mkdir -p $(CURDIR)/debian/tmp/usr/lib/debug
-	for l in `find $(CURDIR)/debian/tmp/usr/lib -name '*.so*'`; do \
-		cp -vdf $$l $(CURDIR)/debian/tmp/usr/lib/debug ; \
-	done
+#	# FIXME: where do we put the debug for the plugins?
+#	mkdir -p $(CURDIR)/debian/tmp/usr/lib/debug
+#	for l in `find $(CURDIR)/debian/tmp/usr/lib -name '*.so*'`; do \
+#		cp -vdf $$l $(CURDIR)/debian/tmp/usr/lib/debug ; \
+#	done
 
 	rm -f $(CURDIR)/debian/tmp/usr/lib/libgoffice-*.la
 
@@ -159,11 +163,11 @@ binary-common:
 	dh_testroot
 	dh_installchangelogs ChangeLog
 ifeq ($(DH_OPTIONS),-s)
-	rm -rvf $(CURDIR)/debian/$(baselibname)-dbg/usr/share/doc/$(baselibname)-dbg
+	rm -rvf $(CURDIR)/debian/$(pdbg)/usr/share/doc/$(pdbg)
 endif
-	dh_install --sourcedir=debian/tmp -X/usr/lib/debug
+	dh_install --sourcedir=debian/tmp
 ifeq ($(DH_OPTIONS),-s)
-	dh_install -p$(baselibname)-dbg --sourcedir=debian/tmp
+	dh_install -p$(pdbg) --sourcedir=debian/tmp
 endif
 
 #	dh_installdebconf -s
@@ -195,7 +199,7 @@ endif
 	dh_scrollkeeper
 	dh_desktop
 ifeq ($(DH_OPTIONS),-s)
-	rm -rvf $(CURDIR)/debian/$(baselibname)-dbg/usr/share/doc/$(baselibname)-dbg
+	rm -rvf $(CURDIR)/debian/$(pdbg)/usr/share/doc/$(pdbg)
 endif
 	dh_link
 	dh_buildinfo
@@ -203,14 +207,14 @@ endif
 #	dh_perl
 #	dh_python
 ifeq ($(DH_OPTIONS),-s)
-	dh_strip -v -Nlibgoffice-0-$(so_major_version)-dbg
+	dh_strip -v --dbg-package=$(pdbg)
 
         # Unfortunately, "-s" overrides "-p" for dh_makeshlibs and by acting
         # on all architecture-dependent packages we would get wrong shlibs
         # here, so we need to undo the "-s".
-	env -u DH_OPTIONS dh_makeshlibs -s -p$(baselibname) -V '$(baselibname) (>= $(upstreamversion))'
+	env -u DH_OPTIONS dh_makeshlibs -s -p$(pruntime) -V '$(pruntime) (>= $(upstreamversion))'
 
-	dh_shlibdeps -s -l debian/$(baselibname)/usr/lib/ -L $(baselibname)
+	dh_shlibdeps -s -l debian/$(pruntime)/usr/lib/ -L $(pruntime)
 endif
 	dh_fixperms
 	dh_installdeb
