Preparations for 0.6.1
svn path=/trunk/; revision=2024

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -9,12 +9,19 @@
 # Uncomment this to turn on verbose mode.
 #export DH_VERBOSE=1
 
+upstreamversion=$(shell dpkg-parsechangelog | grep Version | head -1 | sed -e 's/Version: //g' -e 's/-[A-Za-z0-9+\.]*$$//g')
+versionh=$(shell echo $(upstreamversion) | sed -e 's/\.[^.]*$$//')
+versiont=$(shell echo $(upstreamversion) | sed -e 's/^.*\.//')
+nextupstreamversion=$(shell echo $(versionh).$$(expr $(versiont) + 1))
+
+# The library file name. This goes into the package names (which is why we
+# need to change the periods in it). The debian/* files must match.
+baselibname=$(shell grep -i '^GOFFICE_API_VER=[0-9]' configure | sed -e 's/^.*=/libgoffice-/' -e s/\\./-/g)
 
 # These are used for cross-compiling and for saving the configure script
 # from having to guess our platform (since we know it already)
 DEB_HOST_GNU_TYPE   ?= $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
 DEB_BUILD_GNU_TYPE  ?= $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
-
 
 CFLAGS = -Wall -g
 
@@ -47,7 +54,7 @@ confflags := -v \
 	--prefix=/usr \
 	--mandir=\$${prefix}/share/man \
 	--infodir=\$${prefix}/share/info \
-	--with-html-dir=\$${prefix}/share/doc/libgoffice-0-5-dev/html
+	--with-html-dir=\$${prefix}/share/doc/$(baselibname)-dev/html
 
 # FHS locations
 confflags +=	--prefix=/usr \
@@ -62,18 +69,6 @@ confflags +=    --disable-iso-c \
 
 # Features
 confflags +=    --with-cairo --enable-gtk-doc
-
-upstreamversion=$(shell dpkg-parsechangelog | grep Version | head -1 | sed -e 's/Version: //g' -e 's/-[A-Za-z0-9+\.]*$$//g')
-versionh=$(shell echo $(upstreamversion) | sed -e 's/\.[^.]*$$//')
-versiont=$(shell echo $(upstreamversion) | sed -e 's/^.*\.//')
-nextupstreamversion=$(shell echo $(versionh).$$(expr $(versiont) + 1))
-
-# These values must match their configure.in counterparts
-goffice_version_epoch=0
-goffice_version_major=5
-
-# This goes into the package names; make sure the debian/* files match
-so_version_major=$(shell expr $(goffice_version_epoch) '*' 100 '+' $(goffice_version_major))
 
 source-updates:
 	# Update files/links generated by autotools
@@ -91,6 +86,11 @@ source-updates:
 configure: configure-stamp
 configure-stamp:
 	dh_testdir
+	if ! test -r debian/$(baselibname).install ; then \
+		echo "Packaging files are not set up for base library name $(baselibname). Aborting." ; \
+		exit 1 ; \
+	fi
+	
 	# Add here commands to configure the package.
 
 	rm -rf build && mkdir build
@@ -159,11 +159,11 @@ binary-common:
 	dh_testroot
 	dh_installchangelogs ChangeLog
 ifeq ($(DH_OPTIONS),-s)
-	rm -rvf $(CURDIR)/debian/libgoffice-0-$(so_version_major)-dbg/usr/share/doc/libgoffice-0-$(so_version_major)-dbg
+	rm -rvf $(CURDIR)/debian/$(baselibname)-dbg/usr/share/doc/$(baselibname)-dbg
 endif
 	dh_install --sourcedir=debian/tmp -X/usr/lib/debug
 ifeq ($(DH_OPTIONS),-s)
-	dh_install -plibgoffice-0-$(so_version_major)-dbg --sourcedir=debian/tmp
+	dh_install -p$(baselibname)-dbg --sourcedir=debian/tmp
 endif
 
 #	dh_installdebconf -s
@@ -195,7 +195,7 @@ endif
 	dh_scrollkeeper
 	dh_desktop
 ifeq ($(DH_OPTIONS),-s)
-	rm -rvf $(CURDIR)/debian/libgoffice-0-$(so_version_major)-dbg/usr/share/doc/libgoffice-0-$(so_version_major)-dbg
+	rm -rvf $(CURDIR)/debian/$(baselibname)-dbg/usr/share/doc/$(baselibname)-dbg
 endif
 	dh_link
 	dh_buildinfo
@@ -208,9 +208,9 @@ ifeq ($(DH_OPTIONS),-s)
         # Unfortunately, "-s" overrides "-p" for dh_makeshlibs and by acting
         # on all architecture-dependent packages we would get wrong shlibs
         # here, so we need to undo the "-s".
-	env -u DH_OPTIONS dh_makeshlibs -s -plibgoffice-0-$(so_version_major) -V 'libgoffice-0-$(so_version_major) (>= $(upstreamversion))'
+	env -u DH_OPTIONS dh_makeshlibs -s -p$(baselibname) -V '$(baselibname) (>= $(upstreamversion))'
 
-	dh_shlibdeps -s -l debian/libgoffice-0-$(so_version_major)/usr/lib/ -L libgoffice-0-$(so_version_major)
+	dh_shlibdeps -s -l debian/$(baselibname)/usr/lib/ -L $(baselibname)
 endif
 	dh_fixperms
 	dh_installdeb
